### ISSUE TITLE
How to hide the first option in a select element

### ISSUE THREAD

**Issue by rrickgauer** [rrickgauer/blog#145]
https://codepen.io/cauners/pen/ZEpGQyR

**Comment by rrickgauer** [comment]
### HTML

```html
<select>
  <option selected disabled>Select fruit</option>
  <option>Apples</option>
  <option>Oranges</option>
  <option>Bananas</option>
  <option>Pineapples</option>
</select>
```

### CSS

```css
select option:first-child {
  display: none;
}
```
